[tool.bumpversion]
current_version = "0.0.16"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
regex = false
ignore_missing_version = false
tag = true
sign_tags = false
tag_name = "Helm-v{new_version}"
tag_message = "Bump OpenPinch project version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump OpenPinch project version: {current_version} → {new_version}"
commit_args = ""

[[tool.bumpversion.files]]
filename = "./pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""
